# Generated by Django 4.1.3 on 2022-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='capt',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='imag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
